"use client";

import { useEffect, useState } from "react";

type Preferences = { sensitivity: string; morning: boolean; evening: boolean; browser: boolean; email: boolean; priority: boolean; quiet: boolean };
const defaults: Preferences = { sensitivity: "65", morning: true, evening: true, browser: true, email: false, priority: true, quiet: true };
export default function SettingsPage() {
  const [settings, setSettings] = useState(defaults); const [saved, setSaved] = useState(false);
  useEffect(() => { const stored = localStorage.getItem("gmail-intelligence-settings"); if (stored) setSettings(JSON.parse(stored)); }, []);
  function change(key: keyof Preferences, value: string | boolean) { setSettings((current) => ({ ...current, [key]: value })); setSaved(false); }
  function save() { localStorage.setItem("gmail-intelligence-settings", JSON.stringify(settings)); setSaved(true); }
  return <div className="page settings-page"><h1>Settings</h1><p>Manage your executive intelligence preferences and connected environments.</p><section><h2>♧ &nbsp; Intelligence Engine</h2><small>Control what the AI considers important for your summaries.</small><label>Filtering Aggressiveness <b>High (Executive)</b><input type="range" min="0" max="100" value={settings.sensitivity} onChange={(event) => change("sensitivity", event.target.value)} /><span>Lenient <em>Strict</em></span></label><button className="preference" onClick={() => alert("Topic preferences are applied during the next intelligence run.")}>Topic Preferences <span>☷</span><small>Define keywords and domains to prioritize.</small></button></section><section><h2>◷ &nbsp; Briefing Schedule</h2><Toggle label="Morning Briefing" detail="09:00 AM" checked={settings.morning} onChange={(value) => change("morning", value)} /><Toggle label="Evening Briefing" detail="09:00 PM" checked={settings.evening} onChange={(value) => change("evening", value)} /><label className="timezone">Timezone <select defaultValue="Asia/Kolkata"><option>Asia/Kolkata</option></select></label></section><section><h2>♧ &nbsp; Notifications</h2><Toggle label="Browser notifications" checked={settings.browser} onChange={(value) => change("browser", value)} /><Toggle label="Email notification" checked={settings.email} onChange={(value) => change("email", value)} /><Toggle label="High-priority only" detail="With standard alerts" checked={settings.priority} onChange={(value) => change("priority", value)} /><Toggle label="Quiet hours (10PM - 7AM)" checked={settings.quiet} onChange={(value) => change("quiet", value)} /></section><button className="save-settings" onClick={save}>{saved ? "Saved" : "Save preferences"}</button></div>;
}
function Toggle({ label, detail, checked, onChange }: { label: string; detail?: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="toggle"><span>{label}<small>{detail}</small></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><i /></label>; }
