"use client";

import { useEffect, useRef, useState } from "react";
import { applyThreadAction, correctClassification, getIntelligenceDetail, replyToThread, type IntelligenceDetail } from "../../../lib/api-client";
import { Shell } from "../../shell";

const label = (value: string) => value.replaceAll("_", " ");

export default function DetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [item, setItem] = useState<IntelligenceDetail | null>(null); const [correctedCategory, setCorrectedCategory] = useState(""); const [confirmation, setConfirmation] = useState(""); const [reply, setReply] = useState(""); const replyRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { void params.then(({ id }) => getIntelligenceDetail(id).then(setItem).catch(() => setItem(null))); }, [params]);
  if (!item) return <Shell><div className="page"><div className="empty-state">This intelligence item is unavailable.</div></div></Shell>;
  const action = (name: "delete" | "mark_read" | "mark_unread") => { if (name === "delete" && !window.confirm("Move this email to Gmail Trash?")) return; void applyThreadAction(item.account_id, name, [item.id]).then(() => { setConfirmation(name === "delete" ? "Email moved to Gmail Trash." : "Email updated."); if (name === "delete") window.location.href = "/intelligence"; }).catch(() => setConfirmation("Could not update this email.")); };
  return <Shell><div className="page detail-page"><div className="crumbs"><a href="/intelligence">← Intelligence Feed</a><span>›</span> Message Detail</div><h1>{item.subject}</h1><p className="sender">♟ &nbsp;{item.messages[0]?.from || item.account} <span>•</span> {new Date(item.at).toLocaleString()}</p><hr /><div className="detail-grid"><section><div className="summary-box"><small>✦ &nbsp; Intelligence summary</small><p>{item.summary}</p></div><div className="reply-box"><h2>Reply</h2><textarea ref={replyRef} value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Write a reply…" /><button disabled={!reply.trim()} onClick={() => void replyToThread(item.account_id, item.id, reply).then(() => { setReply(""); setConfirmation("Reply sent."); }).catch(() => setConfirmation("Could not send reply. Reconnect Gmail if permission is missing."))}>Send reply</button></div><div className="why-box"><h2>▣ &nbsp; Why we classified it this way</h2>{item.explanation.reasons.map((reason) => <p key={reason.signal}>◉ &nbsp;{reason.label}</p>)}</div></section><aside className="analytics"><header className="analytics-header"><b>Message analytics</b><span className="category">{label(item.category)}</span></header><section className="priority-metric"><small>Priority score</small><strong>{item.priority}<em>/100</em></strong><i><span style={{ width: `${item.priority}%` }} /></i></section><section className="correction-control"><label>Correct classification<select value={correctedCategory} onChange={(event) => setCorrectedCategory(event.target.value)}><option value="">Choose a category</option>{item.categories.map((category) => <option key={category} value={category}>{label(category)}</option>)}</select></label><button className="secondary" disabled={!correctedCategory} onClick={() => void correctClassification(item.id, correctedCategory).then((updated) => { setItem({ ...item, ...updated }); setCorrectedCategory(""); setConfirmation("Classification corrected"); }).catch(() => setConfirmation("Could not save classification correction."))}>Save correction</button></section><section className="message-actions"><button onClick={() => replyRef.current?.focus()}>Reply</button><button onClick={() => action(item.is_unread ? "mark_read" : "mark_unread")}>{item.is_unread ? "Mark read" : "Mark unread"}</button><button className="delete" onClick={() => action("delete")}>Delete</button></section><a className="gmail-link" href={item.gmail_url} target="_blank" rel="noreferrer">View original in Gmail</a>{confirmation && <small className="action-notice">{confirmation}</small>}</aside></div></div></Shell>;
}
