"use client";

import { useEffect, useState } from "react";
import { applyThreadAction, correctClassification, getIntelligenceDetail, replyToThread, type IntelligenceDetail } from "../../../lib/api-client";
import { Shell } from "../../shell";

const categories = ["action_required", "opportunity", "important_keep", "personal_conversation", "notification", "otp_verification", "promotional_bulk", "unclear"];

export default function DetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [item, setItem] = useState<IntelligenceDetail | null>(null); const [correctedCategory, setCorrectedCategory] = useState(""); const [confirmation, setConfirmation] = useState(""); const [reply, setReply] = useState("");
  useEffect(() => { void params.then(({ id }) => getIntelligenceDetail(id).then(setItem).catch(() => setItem(null))); }, [params]);
  if (!item) return <Shell><div className="page"><div className="empty-state">This intelligence item is unavailable.</div></div></Shell>;
  const action = (name: "archive" | "delete" | "mark_read" | "mark_unread") => { if (name === "delete" && !window.confirm("Move this email to Gmail Trash?")) return; void applyThreadAction(item.account_id, name, [item.id]).then(() => { setConfirmation(name === "delete" ? "Email moved to Gmail Trash." : "Email updated."); if (name === "archive" || name === "delete") window.location.href = "/intelligence"; }).catch(() => setConfirmation("Could not update this email.")); };
  return <Shell><div className="page detail-page"><div className="crumbs"><a href="/intelligence">← Intelligence Feed</a><span>›</span> Message Detail</div><h1>{item.subject}</h1><p className="sender">♟ &nbsp;{item.messages[0]?.from || item.account} <span>•</span> {new Date(item.at).toLocaleString()}</p><hr /><div className="detail-grid"><section><div className="summary-box"><small>✦ &nbsp; Intelligence summary</small><p>{item.summary}</p></div><div className="reply-box"><h2>Reply</h2><textarea value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Write a reply…" /><button disabled={!reply.trim()} onClick={() => void replyToThread(item.account_id, item.id, reply).then(() => { setReply(""); setConfirmation("Reply sent."); }).catch(() => setConfirmation("Could not send reply. Reconnect Gmail if permission is missing."))}>Send reply</button></div><div className="why-box"><h2>▣ &nbsp; Why we classified it this way</h2>{item.explanation.reasons.map((reason) => <p key={reason.signal}>◉ &nbsp;{reason.label}</p>)}</div></section><aside className="analytics"><b>Message analytics</b><small>Category</small><span className="category">△ &nbsp;{item.category.replaceAll("_", " ")}</span><label>Correct classification<select value={correctedCategory} onChange={(event) => setCorrectedCategory(event.target.value)}><option value="">Choose a category</option>{categories.map((category) => <option key={category} value={category}>{category.replaceAll("_", " ")}</option>)}</select></label><button disabled={!correctedCategory} onClick={() => void correctClassification(item.id, correctedCategory).then((updated) => { setItem({ ...item, ...updated }); setCorrectedCategory(""); setConfirmation("Classification corrected"); }).catch(() => setConfirmation("Could not save classification correction."))}>Save correction</button><div className="email-actions"><button onClick={() => action("archive")}>Archive</button><button onClick={() => action("mark_read")}>Mark read</button><button onClick={() => action("mark_unread")}>Mark unread</button><button className="delete" onClick={() => action("delete")}>Delete</button></div>{confirmation && <small>{confirmation}</small>}<hr /><label>Priority score <strong>{item.priority}<em>/100</em></strong><i><span style={{ width: `${item.priority}%` }} /></i></label><label>AI confidence <strong>{Math.round(item.confidence * 100)}<em>%</em></strong><i><span style={{ width: `${item.confidence * 100}%` }} /></i></label><button onClick={() => window.open(item.gmail_url, "_blank", "noopener,noreferrer")}>✉ &nbsp; View original in Gmail</button></aside></div></div></Shell>;
}
