"use client";

import { useEffect, useRef, useState } from "react";
import { connectGmail, deleteAccount, getAccounts, getSyncRuns, syncAccount, type Account, type SyncRun } from "../../lib/api-client";

export default function AccountsPage() {
  const syncing = useRef(new Set<string>());
  const [accounts, setAccounts] = useState<Account[]>([]); const [runs, setRuns] = useState<Record<string, SyncRun[]>>({}); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = async (refresh = false) => { const current = await getAccounts(refresh); setAccounts(current); setRuns(Object.fromEntries(await Promise.all(current.map(async (account) => [account.id, await getSyncRuns(account.id).catch(() => [])] as const)))); };
  useEffect(() => { void load(true).catch(() => setError("Unable to load connected accounts.")); setError(new URLSearchParams(window.location.search).get("error")); }, []);
  async function sync(id: string) { if (syncing.current.has(id)) return; syncing.current.add(id); setBusy(id); setError(null); try { await syncAccount(id); await load(true); } catch (error) { setError(error instanceof Error ? error.message : "Sync failed. Try again in a moment."); } finally { syncing.current.delete(id); setBusy(null); } }
  async function disconnect(id: string) { if (!window.confirm("Disconnect this Gmail account?")) return; setBusy(id); try { await deleteAccount(id); await load(true); } catch { setError("Could not disconnect this account."); } finally { setBusy(null); } }
  return <div className="page accounts"><h1>Connected Gmail Accounts</h1><p>Manage your connected inboxes and synchronization settings. Intelligence processing requires active connections.</p>{error && <p className="form-error" role="alert">{error}</p>}<section className="account-grid">{accounts.map((account) => <article className="account-tile" key={account.id}><div><i>✉</i><h2>{account.name || account.email.split("@", 1)[0]}<small>{account.email}</small></h2><span className="connected">● Connected</span></div><p><span>Last connected</span><b>{account.last_synced_at ? new Date(account.last_synced_at).toLocaleString() : "Not synced yet"}</b></p><p><span>Intelligence Sync</span><b className="active">◉ Active</b></p><details className="sync-log"><summary>Sync log</summary>{runs[account.id]?.map((run) => <p key={`${run.started_at}:${run.status}`}><b>{run.status}</b><span>{new Date(run.started_at).toLocaleString()} · {run.messages_examined} examined / {run.messages_imported} imported</span>{run.error_summary && <small>{run.error_code}: {run.error_summary}</small>}</p>) || <p>No sync attempts yet.</p>}</details><footer><button disabled={busy === account.id} onClick={() => void sync(account.id)}>{busy === account.id ? "Syncing…" : "Sync Now"}</button><button disabled={busy === account.id} onClick={() => void disconnect(account.id)}>Disconnect</button></footer></article>)}<button className="add-account" onClick={() => void connectGmail()}><i>＋</i><b>Connect another Gmail</b><span>Authorize a new account to bring more context into your intelligence dashboard.</span></button></section></div>;
}
