"use client";

import { useEffect, useMemo, useState } from "react";
import { applyThreadAction, getAccounts, getCleanup, type Account, type Cleanup } from "../../../lib/api-client";
import { Shell } from "../../shell";

export default function CleanupPage() {
  const [data, setData] = useState<Cleanup | null>(null); const [accounts, setAccounts] = useState<Account[]>([]); const [account, setAccount] = useState(""); const [selected, setSelected] = useState<Set<string>>(new Set()); const [notice, setNotice] = useState("");
  const load = () => void getCleanup(account || undefined).then(setData).catch(() => setData(null));
  useEffect(() => { void getAccounts().then(setAccounts).catch(() => setAccounts([])); }, []); useEffect(load, [account]);
  const selectedIds = useMemo(() => [...selected], [selected]);
  const toggleGroup = (ids: string[]) => setSelected((current) => { const next = new Set(current); const all = ids.every((id) => next.has(id)); ids.forEach((id) => all ? next.delete(id) : next.add(id)); return next; });
  const remove = (ids: string[]) => { if (!ids.length || !window.confirm(`Move ${ids.length} selected email${ids.length === 1 ? "" : "s"} to Gmail Trash?`)) return; const chosen = (data?.groups.flatMap((group) => group.items) || []).filter((item) => ids.includes(item.id)); const byAccount = new Map<string, string[]>(); chosen.forEach((item) => byAccount.set(item.account_id, [...(byAccount.get(item.account_id) || []), item.id])); void Promise.all([...byAccount].map(([accountId, threadIds]) => applyThreadAction(accountId, "delete", threadIds))).then(() => { setNotice(`${ids.length} email${ids.length === 1 ? "" : "s"} moved to Gmail Trash.`); setSelected(new Set()); load(); }).catch(() => setNotice("Could not move the selected emails to Gmail Trash.")); };
  return <Shell><div className="page cleanup"><header className="cleanup-heading"><div><h1>Cleanup</h1><p>Review lower-priority communications and move selected items to Gmail Trash.</p></div><div><small>Total impact</small><b>{data?.total_impact ?? 0}</b><span>emails available for cleanup</span></div></header><select className="cleanup-account" value={account} onChange={(event) => setAccount(event.target.value)}><option value="">All accounts</option>{accounts.map((item) => <option value={item.id} key={item.id}>{item.name || item.email}</option>)}</select><section className="cleanup-grid">{data?.groups.map((group) => { const ids = group.items.map((item) => item.id); const chosen = ids.filter((id) => selected.has(id)); return <article className="cleanup-card" key={group.key}><header><i>{group.key === "promotional" ? "◇" : group.key === "notifications" ? "♧" : "⌁"}</i><b>{group.items.length}</b></header><h2>{group.title}</h2><p>{group.description}</p><div className="cleanup-actions"><button onClick={() => toggleGroup(ids)}>Select all</button><button disabled={!chosen.length} onClick={() => remove(chosen)}>Delete</button></div><div className="cleanup-items">{group.items.map((item) => <label key={item.id}><input type="checkbox" checked={selected.has(item.id)} onChange={() => setSelected((current) => { const next = new Set(current); next.has(item.id) ? next.delete(item.id) : next.add(item.id); return next; })} />{item.subject}</label>)}</div></article>; })}</section>{selectedIds.length > 0 && <button className="archive-selected" onClick={() => remove(selectedIds)}>Delete selected ({selectedIds.length})</button>}{notice && <p className="cleanup-notice">{notice}</p>}</div></Shell>;
}
