"use client";

import { useEffect, useMemo, useState } from "react";
import { getAccounts, getIntelligence, getIntelligenceOverview, type Account, type IntelligenceItem, type IntelligenceOverview } from "../../lib/api-client";
import { Shell } from "../shell";

const categories = ["action_required", "opportunity", "important_keep", "personal_conversation", "notification", "otp_verification", "promotional_bulk", "unclear"] as const;
const filters = [["all", "All"], ...categories.map((category) => [category, category.replaceAll("_", " ")]), ["review", "Review"]] as const;

export default function IntelligencePage() {
  const [items, setItems] = useState<IntelligenceItem[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [overview, setOverview] = useState<IntelligenceOverview | null>(null); const [search, setSearch] = useState(""); const [filter, setFilter] = useState<(typeof filters)[number][0]>("all"); const [account, setAccount] = useState("");
  useEffect(() => { setSearch(new URLSearchParams(window.location.search).get("q") || ""); void getAccounts().then(setAccounts).catch(() => setAccounts([])); }, []);
  useEffect(() => { void getIntelligence({ accountId: account || undefined, category: filter === "all" || filter === "review" ? undefined : filter, review: filter === "review" }).then(setItems).catch(() => setItems([])); void getIntelligenceOverview(account || undefined).then(setOverview).catch(() => setOverview(null)); }, [account, filter]);
  const visible = useMemo(() => items.filter((item) => `${item.subject} ${item.snippet}`.toLowerCase().includes(search.toLowerCase())), [items, search]);
  const metric = (category: string, label: string) => <div className="overview-metric" key={category}><b>{overview?.categories[category] ?? 0}</b><span>{label}</span></div>;
  return <Shell><div className="page intelligence"><h1>Intelligence</h1><div className="intelligence-account">Gmail: {accounts.find((item) => item.id === account)?.email || accounts[0]?.email || "No connected account"}<select value={account} onChange={(event) => setAccount(event.target.value)}><option value="">All accounts</option>{accounts.map((item) => <option value={item.id} key={item.id}>{item.name || item.email}</option>)}</select></div><section className="overview"><header><h2>Inbox overview</h2><small>{overview?.total_analyzed ?? 0} emails analyzed</small></header><div className="overview-grid">{metric("action_required", "Action Required")}{metric("opportunity", "Opportunities")}{metric("important_keep", "Important")}{metric("personal_conversation", "Personal")}{metric("notification", "Notifications")}{metric("promotional_bulk", "Promotional")}{metric("otp_verification", "OTP")}{metric("unclear", "Unclear")}</div><footer><span><b>{overview?.needs_attention ?? 0} need attention</b><small>Action required and important</small></span><span><b>{overview?.low_priority ?? 0} low-priority emails</b><small>Safe promotional and notification review</small></span><span><b>{overview?.promotional ?? 0} promotional · {overview?.notifications ?? 0} notifications</b><small>Available in cleanup</small></span><a href="/intelligence/cleanup">Review cleanup</a></footer></section><div className="filter-row"><div className="tabs">{filters.map(([value, label]) => <button onClick={() => setFilter(value)} className={filter === value ? "active" : ""} key={value}>{label}</button>)}</div></div><small className="list-label">Emails</small><input className="mobile-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search insights…" /> <section className="intelligence-list">{visible.map((item) => <a href={`/intelligence/${item.id}`} className={`insight-row ${item.category === "action_required" ? "urgent" : ""}`} key={item.id}><i>{item.category === "action_required" ? "!" : "◇"}</i><div><small>{item.account}</small><h2>{item.subject}</h2><span>{item.category.replaceAll("_", " ")}</span>{item.priority >= 80 && <span>High priority</span>}</div><time>Priority {item.priority}　›</time></a>)}{!visible.length && <div className="empty-state">No intelligence matches this view.</div>}</section></div></Shell>;
}
